name: "lol-builds_devcontainer"

services:
  devbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: builds_devbox
    env_file:
      - .env
    volumes:
      - ../:/workspace:cached
      - codex-state:/home/marko/.codex
    ports:
      - 5173:5173
      - 8081:8080
      - 55051:55051
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: builds_clickhouse
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # TCP Native
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_PASSWORD=default

volumes:
  clickhouse_data:
  codex-state:
