version: "3.8"

name: "lol-builds_devcontainer"

services:
  devbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devbox
    env_file:
      - .env
    volumes:
      - ../:/workspace:cached
    ports:
      - 5173:5173
      - 8223:22
    depends_on:
      - clickhouse
      - nats

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # TCP Native
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222" # client
      - "8222:8222" # monitoring HTTP
    command: ["-js", "-m", "8222"]

volumes:
  clickhouse_data:
